TileDB-Inc/tiledb-rs

- .gitignore
- build.rs
Implements a likely not portable means of enabling `cargo test` to run with `libtiledb.so` in its rpath without any system hackery.
> Set LD_LIBRARY_PATH for `cargo test`

- Cargo.toml
- src/array/mod.rs
Both tempdir and lazy_static should be in the `[dev-dependencies]` section so that we're not forcing them on downstream users. Secondly I removed lazy_static in favor of creating a TempDir per test to avoid sharing global state in tests as well as error localization in the very unlikely situation core ever creates a non-writable file.
> Fixup Dependencies

- tiledb/api/src/array/dimension.rs
- tiledb/api/src/array/domain.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema.rs
This pull request adds an equivalent of the `tiledb_array_schema_load` function which opens an array schema from a URI.
Prior work with array schema *creation* put the Domain in as a field in the `ArraySchema`, so most of the implementation here is actually about that.  `ArraySchema::open` calls `Domain::load` which fetches into Rust the information needed from the C API.
"Prior work" was the focus on the `quickstart_dense` example which creates, rather than reads, an array.  In that example we had to make sure that the Domain lifetime was at least as long as the Schema lifetime, and then Domain has a vector of Dimension for the same reason.
Since the tests for this naturally want to ask about the dimensions, there are also changes to the `Domain::dimension` function, specifically to …
> Add Schema::open with simple quickstart_dense test

- tiledb/api/examples/quickstart_dense.rs
- tiledb/api/src/array/attribute.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema.rs
This adds a bunch more pretty-much-straightforward methods to the Attribute and Schema classes.
Along the way we also stylize the `Attribute` struct in a manner similar to `Schema`, `Domain`, and `Dimension`.  We split off a `Builder` class for the setter methods to construct a new `Attribute` and add a `&'ctx Context` member to make all of the methods more convenient.
This surely conflicts with #6 which we should merge first.
> Attribute has a Context member and Builder like the other structs, and add a bunch more getters/setters for Attribute and Schema

- tiledb/sys/.gitignore
- tiledb/sys/Makefile
- tiledb/sys/README.md
The usage for this is included in the `tiledb/sys/README.md` docs. But for anyone too lazy to look at that, the basics are:
```bash
cd tiledb/sys
make
```
If you get errors about bindgen or ripgrep do the following on macOS:
```bash
cargo install bindgen-cli
brew install ripgrep
```
> Add tooling for listing unwraped API functions

- tiledb/api/src/context.rs
We can't guarantee that any given VFS backend is unavailable at any given time so we'll just remove the test for missing backends.
> Remove flaky is_supported_fs test

- tiledb/api/Cargo.toml
- tiledb/api/src/array/attribute.rs
- tiledb/api/src/array/schema.rs
- tiledb/api/src/lib.rs
- tiledb/arrow/src/datatype.rs
- tiledb/test/src/attribute.rs
- tiledb/test/src/lib.rs
The addition of the Attribute pbt strategy revealed that the circular dependency did not actually work.
> Remove test crate circular dependency and add arbitrary Attribute pbt strategy

- .github/workflows/build-and-test.yml
- .github/workflows/nigthtly-stable.yml
- tiledb/api/src/lib.rs
- tiledb/api/src/vfs.rs
- tiledb/sys/src/lib.rs
- tiledb/sys/src/types.rs
- tiledb/sys/src/version.rs
- tiledb/sys/src/vfs.rs
This covers the VFS API. I've not covered the bucket APIs with tests becauase I don't feel like adding a CI object store definition. Given that these are extensively tested during C++ builds I'm not overly concerned about the lack of coverage. I'm sure in the future I'll get around to setting things up in CI to exercise things when I switch to improving coverage mode.
> Add wrappers for VFS

- tiledb/api/src/vfs.rs
- tiledb/sys/src/vfs.rs
These weren't very Rusty on my first attempt. After some discussion with Ryan, he reminded me that FnMut is a thing and it turns out is actually usable as an argument being passed to a C API. Its a bit nutty on the implementation, but it seems to work just fine.
> Fix the VFS::ls and VFS::ls_recursive APIs

- tiledb/api/src/array/schema.rs
- tiledb/sys/src/datatype.rs
- tiledb/test/src/attribute.rs
- tiledb/test/src/datatype.rs
- tiledb/test/src/dimension.rs
- tiledb/test/src/domain.rs
- tiledb/test/src/lib.rs
- tiledb/test/src/schema.rs
There are some restrictions on dimension types for dense arrays, for which adding some `Datatype` query functions was very helpful.
> Implement strategy for arbitrary Schema generation, for dense or sparse arrays

- tiledb/api/src/array/attribute.rs
- tiledb/api/src/array/dimension.rs
- tiledb/api/src/array/domain.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema.rs
- tiledb/api/src/config.rs
- tiledb/api/src/context.rs
- tiledb/api/src/filter.rs
- tiledb/api/src/filter_list.rs
- tiledb/api/src/query/mod.rs
- tiledb/api/src/query/subarray.rs
- tiledb/api/src/vfs.rs
First, all instances of as_mut_ptr() have been replaced with the now standard capi(). Both of these do exactly the same thing, this just unifies the naming convention.
Secondly, I've moved almost everything over to using the RawThing/Thing pattern where RawThing is just a deref-able enum containing the ffi pointer. This removes the need for all of the instances of as_mut_ptr_ptr and Default implementations that were sketchy at best.
Filters haven't been updated yet, but they will be as part of PR #19.
> Rename as_mut_ptr() to capi() for consistency

- tiledb/api/src/array/attribute.rs
- tiledb/api/src/array/dimension.rs
- tiledb/api/src/filter.rs
- tiledb/api/src/filter_list.rs
- tiledb/sys/src/filter_type.rs
This updates the first APIs I wrapped to use the both the builder pattern as well as tracking their own context references.
> Rewrap Filter and FilterList

- Cargo.lock
- tiledb/api/Cargo.toml
- tiledb/api/src/array/attribute.rs
- tiledb/api/src/convert.rs
- tiledb/api/src/datatype.rs
- tiledb/api/src/error.rs
- tiledb/api/src/lib.rs
- tiledb/test/src/attribute.rs
To test Arrow schema to/from TileDB schema conversion, we will want to test invertability.  That will require some means of checking that the Attribute we get out is the same as the Attribute we put in.  `PartialEq` is a natural choice for this, so this pull request does most of the work to implement it for Attribute.
What's missing is the filter comparison, and that will probably be done as a follow-up after #19 is merged.
> impl PartialEq for Attribute

- tiledb/api/Cargo.toml
- tiledb/api/src/array/attribute.rs
- tiledb/api/src/array/dimension.rs
- tiledb/api/src/datatype.rs
- tiledb/api/src/filter.rs
- tiledb/api/src/filter_list.rs
- tiledb/api/src/lib.rs
- tiledb/api/tests/enum_conversion_tests.rs
- tiledb/arrow/src/attribute.rs
- tiledb/sys/src/datatype.rs
- tiledb/test/src/attribute.rs
- tiledb/test/src/filter.rs
- tiledb/test/src/lib.rs
- tiledb/test/src/schema.rs
The missing piece from `Attribute::eq` was the filter pipeline.  To get this in there with the testing infrastructure we have and/or will need, we need to do `Debug`, `Eq`, `Serialize` and `Deserialize` for `FilterList` and `Filter`.
That turns out to require a bunch of things:
- to keep the `sys` crate with minimal dependencies, I moved `Datatype` to the `api` crate where it can `#[derive(Deserialize, Serialize)]`.  This also is a big step towards keeping `ffi::` out of the public APIs.
- not strictly a requirement, but the `enum FilterData` is really useful because it can `#[derive(PartialEq)]` which helps prevent us developers from making mistakes.  Now those mistakes can live in `Filter::create` and/or `Filter::filter_data` instead.
- `FilterData::transform_datatype` is an internal C …
> Scaffolding to support generating arbitrary filter pipelines

- .github/actions/install-tiledb/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/nigthtly-stable.yml
This moves the installation of TileDB to a composite action so it can be reused between workflows. The nightly workflow was broken because I forgot to set the `RELEASES_URL` environment variable.
> Fix nightly build CI workflow

- tiledb/api/src/array/attribute.rs
- tiledb/api/src/array/dimension.rs
- tiledb/api/src/array/domain.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema.rs
- tiledb/arrow/src/attribute.rs
- tiledb/arrow/src/dimension.rs
- tiledb/arrow/src/filter.rs
- tiledb/arrow/src/lib.rs
- tiledb/arrow/src/schema.rs
- tiledb/test/src/dimension.rs
- tiledb/test/src/domain.rs
- tiledb/test/src/schema.rs
This pull request implements functions to convert between TileDB schema and Arrow schema.
As in #28, we use a serializable objects to store details about the TileDB schema and/or dimension which do not have a natural field in the Arrow Schema.
There aren't any notable new designs here, just lots of details which were missing including several `PartialEq` implementations, some fields from `Debug`, some `ffi` methods which were not implemented yet, and some updates to the proptest strategies.  Among the missing methods were the Schema's filter list setters and getters - these depend on the Domain to generate sound values, so I was unable to add them to proptest as we have discussed as length in Slack.
Resolves sc#43826.
> Implement conversion between TIleDB Schema and Arrow Schema

- tiledb/api/src/array/attribute.rs
- tiledb/api/src/array/dimension.rs
- tiledb/api/src/array/domain.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema.rs
- tiledb/api/src/filter.rs
- tiledb/api/src/filter_list.rs
- tiledb/api/src/lib.rs
- tiledb/arrow/src/attribute.rs
- tiledb/arrow/src/dimension.rs
- tiledb/arrow/src/filter.rs
- tiledb/arrow/src/schema.rs
- tiledb/test/src/attribute.rs
- tiledb/test/src/dimension.rs
- tiledb/test/src/domain.rs
- tiledb/test/src/filter.rs
- tiledb/test/src/schema.rs
Prior to this pull request, our proptest strategies have generated our API structs directly - the Attribute, Dimension, Domain, Schema, etc.  This has led to a lot of difficulty as our strategies get more and more complex. Without being able to deeply clone an object we have no way to have a strategy depend on the contents of a Domain, for example, and we are reluctant to add a deep clone function.
This pull request modifies our strategies to instead produce a set of input values which can be used to construct our structures instead.  This way we can have no qualms about deep cloning, and we might even be able to benefit further from the new cloneable objects in the future.
There are other benefits briefly described in the shortcut story.
For each of our API objects, we add another …
> Update proptest strategies to produce a set of inputs to our APIs, instead of the structs directly

- tiledb/api/examples/quickstart_dense.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/context.rs
- tiledb/api/src/lib.rs
- tiledb/api/src/query/subarray.rs
In a different branch I added `DimensionKey` to use the dimension range functions with an index or name lookup. This adds the same facility to `Subarray`.
> Add comments to quickstart_dense.rs and also make Subarray::dimension_range_typed more flexible

- Cargo.lock
- Cargo.toml
- tiledb/api/Cargo.toml
- tiledb/api/src/array/attribute.rs
- tiledb/api/src/array/dimension.rs
- tiledb/api/src/array/domain.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema.rs
- tiledb/api/src/config.rs
- tiledb/api/src/context.rs
- tiledb/api/src/datatype.rs
- tiledb/api/src/error.rs
- tiledb/api/src/filter.rs
- tiledb/api/src/lib.rs
- tiledb/api/src/vfs.rs
- tiledb/arrow/Cargo.toml
- tiledb/arrow/src/attribute.rs
- tiledb/arrow/src/dimension.rs
- tiledb/arrow/src/lib.rs
- tiledb/arrow/src/schema.rs
This story is mostly about ensuring Sync and Send for our custom Error type.  To do that, we must remove the `*mut ffi::` raw pointer.  And then, since we're in the area, we can update our Error to have less reliance, a practice which is discouraged in the Rust documentation.
To that end, we change `Error` to be an `enum` for different error classes, and remove `From<String>`.
We add the dependency `thiserror` for use with our Error type, and add `anyhow` to generalize errors coming from other crates (such as with deserialization).
Resolves sc#44032.
> Better programmatic information for Error type, and ensure Sync/Send

- tiledb/api/src/array/attribute.rs
- tiledb/api/src/array/dimension.rs
- tiledb/api/src/array/domain.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema.rs
- tiledb/api/src/context.rs
- tiledb/api/src/filter.rs
- tiledb/api/src/filter_list.rs
- tiledb/api/src/lib.rs
- tiledb/api/src/query/mod.rs
- tiledb/api/src/query/subarray.rs
- tiledb/api/src/vfs.rs
- tiledb/arrow/src/dimension.rs
- tiledb/arrow/src/schema.rs
This pull request does a few things which hopefully should improve stability of our API.
1) in a few cases the code wrote in the assumption that libtiledb would return `TILEDB_OK`.  We discussed and agreed not to do this, so this request fixes those.
2) we add the `Context::capi_return` function and move all C API return value checking in that function. There are more return codes than just `TILEDB_OK` and `TILEDB_ERR`, and this makes it substantially easier for us to accommodate those into possibly different kinds of Rust API errors.
3) we add the ContextBound trait which is just a cute way to give everything `fn context(&self) -> &'ctx Context`.  This is helpful for propagating the `capi_return` function described above, and also might be handy for users of the API.
Resolves sc#44161
> capi_return function, ContextBound trait, fix methods which do not return Result

- Cargo.lock
- tiledb/api/Cargo.toml
- tiledb/api/src/array/attribute/strategy.rs
- tiledb/api/src/array/domain/strategy.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/array/schema/strategy.rs
- tiledb/api/src/array/strategy.rs
- tiledb/api/src/filter/mod.rs
- tiledb/api/src/filter/strategy.rs
- tiledb/arrow/src/attribute.rs
- tiledb/arrow/src/filter.rs
- tiledb/arrow/src/schema.rs
Even though you can create a schema, that doesn't mean it can turn into an array!  This pull request found that out and then modifies our schema generation strategies so that our test does what we would like.
A lot of the complexity is driven by the constraints on the webp filter, and also by the proptest library guidance to avoid `proptest_filter`.  Fortunately our strategy already generates a Domain before it generates the attribute filters, so we can pass the Domain down to the filter pipeline generator and use it to determine what we're able to do.
The other main challenge is the dimension/attribute name uniqueness. Solving this with `proptest_filter` does not work at all because shrinking does not work on our types yet.  I started out trying to solve this by generating a set of names …
> Add test that our arbitrary schemata can actually create an array, and update strategies to make it so

- tiledb/api/src/array/attribute/strategy.rs
- tiledb/api/src/array/dimension/strategy.rs
- tiledb/api/src/array/schema/strategy.rs
- tiledb/api/src/filter/list.rs
- tiledb/api/src/filter/strategy.rs
- tiledb/arrow/src/filter.rs
The strategy which generates filter pipelines is rather complex because it has to ensure that the output from each filter chains to the input from the next filter.  The strategy has to first choose an input datatype and a number of filters, and then it basically folds over those to produce the pipeline.
The end result sure looks a lot like a vector, and we'd probably like it to shrink like one when tests fail.  But the folding strategy basically does not work at all with this, and some light testing makes it very unclear if the simplification step ever actually does reduce the number of filters in the pipeline.
So here we implement `Arbitrary` for `FilterListData`, using the same code to produce the initial pipeline, and then we shrink the pipeline by trimming off the end (which we can do …
> Implement proptest shrinking for filter pipeline

- tiledb/api/src/stats.rs
It was very unlikely that we would have paniced while this string was alive, but if we did and someone handles the panic, then the string would leak. Adding a RawStatsString wrapper for the pointer removes that edge case.
> Add RawStatsString

- tiledb/api/src/context.rs
Ryan mentioned running the tests through valgrind and it catching a leak around the stats code. I ended up bored and figured out how to run the tests through macOS Instruments which pointed directly at my broken wrapping of `tiledb_context_get_stats`. The RawStatsString I wrote the other day fixes it right up.
Underlying bug was that I just forgot to free an empty string returned by core.
> Fix leak in tiledb_context_get_stats

- Cargo.lock
- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/dimension/mod.rs
- tiledb/api/src/array/domain/mod.rs
- tiledb/api/src/array/enumeration/mod.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/filter/list.rs
- tiledb/api/src/filter/mod.rs
- tiledb/api/src/query/mod.rs
- tiledb/api/src/query/subarray.rs
- tiledb/api/src/vfs.rs
- tiledb/proc-macro/Cargo.toml
- tiledb/proc-macro/src/context.rs
- tiledb/proc-macro/src/lib.rs
- tiledb/proc-macro/tests/context.rs
This pull request enables writing `#[derive(ContextBound)]`.  The implementation looks for a field with an attribute either `#[context]`, which is the context field to return directly, or a field with attribute `#[base(ContextBound)]` which indicates that the impl should be deferred to the base field.
There are a few `unimplemented!()`s, but what *is* implemented is enough to replace all the manual impls in our current code, as well as satisfy the proc macro unit test which simulates how we will want to use this in the near future for the query API adapters.
> Enable #[derive(ContextBound)]

- Cargo.lock
- tiledb/api/src/array/dimension/strategy.rs
- tiledb/utils/Cargo.toml
- tiledb/utils/src/numbers.rs
There were two underlying but related bugs in the dimension range and extent generation. The first bug found and fixed was when we had floating point values with sufficiently large exponents that caused this relationship: `x + y == x`. I.e., "a vary large value + 1 == the same value". This is due to floating point resolution at resolution being larger than 1 when the exponent is large enough. For this bug, the end result was that our extent bounds ended up being `[1.0, 0.0)` which is an empty range that causes proptest to panic internally.
A second version of this same bug also existed for integral values when we had the case of `x + 1 = y`. In this case, due to the open rhs of a range, we ended up with `[1.0, 1.0)` which is also empty.
Once those were fixed, the next issue was based on …
> Fix domain shrinking proptest

- .github/workflows/nigthtly-ci.yml
- .github/workflows/pr-api-coverage.yml
- .github/workflows/pr-build-and-test.yml
- .github/workflows/pr-ci.yml
- tiledb/api/src/string.rs
- tiledb/api/src/vfs.rs
- tiledb/sys/ignored.rs
- tiledb/sys/remapped.rs
- tiledb/sys/src/attribute.rs
- tiledb/sys/src/capi_enum.rs
- tiledb/sys/src/context.rs
- tiledb/sys/src/datatype.rs
- tiledb/sys/src/filesystem.rs
- tiledb/sys/src/filter.rs
- tiledb/sys/src/filter_type.rs
- tiledb/sys/src/stats.rs
- tiledb/sys/src/string.rs
- tiledb/sys/src/vfs.rs
- tools/api-coverage/src/main.rs
This fixes all of our existing API discrepancies and requires that no more are introduced (i.e., CI will fail if whatever declarations in `tiledb/sys` don't exactly match what bindgen generates unless they are remapped).
I've also fixed up the output so we can use it as a build status on GitHub.
> Add API Coverage CI Job

- .github/workflows/pr-ci.yml
I just noticed I copy pasta'ed the wrong default branch name when updating CI the other day.
> Replace dev with main in CI

- tiledb/api/src/array/attribute/arrow.rs
- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/attribute/strategy.rs
- tiledb/api/src/array/dimension/arrow.rs
- tiledb/api/src/array/dimension/mod.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/proc-macro/src/context.rs
- tiledb/utils/src/option.rs
First we use the `DimensionKey` (soon to be re-named, from the fragment info PR) to enable looking up an attribute by name.  Then we also add `crate::array::schema::Field` to encapsulate commonalities to Dimension and Attribute, for use cases where it does not matter whether a schema field is a dimension or attribute.
> Improve field lookup from schema API

- tiledb/api/examples/quickstart_dense.rs
- tiledb/api/examples/using_tiledb_stats.rs
- tiledb/api/src/query/mod.rs
- tiledb/api/src/query/subarray.rs
The previous builder was based on my misunderstanding of how to use the subarray API.  The pattern enforced by the builder prevented more than one dimension range from being used, because `SubarrayBuilder::dimension_range_typed` returned back the query builder.  Now it returns back the Subarray builder so that a more complex subarray can be constructed before changing back to the Query building state.
`cargo run --example quickstart_dense` before and after these changes shows that we now produce a correct result.
> Fix subarray builder to correctly use C API

- .github/workflows/pr-api-coverage.yml
- tools/api-coverage/src/api.rs
- tools/api-coverage/src/main.rs
Before this change we weren't catching any of the calls that happened inside macros which means we were missing a few things that were only called from within `fn_typed!`.
> Process the output of `cargo expand` for API calls

- tiledb/api/src/query/buffer.rs
- tiledb/api/src/query/read/callback.rs
- tiledb/api/src/query/write/input.rs
There were two tests that were each taking over twenty seconds to complete. After some investigation with Ryan the other day, we narrowed it own to constantly reparsing the pattern passed to `string_regex`. The idea then was to put all of our `string_regex` patterns behind a lazy_static. However, it turns out that its none of our strategies causing the issue.
The issue is `vec(any::<String>(), 0..1024)`. That will constantly re-parse the default `string_regex` pattern of `\\PC*`. To avoid that slowness I've created a new strategy that generates `Vec<Vec<u8>>` and then prop_maps the inner vector into a String. This works because I'm only generating `u8` values in the range [1, 127) which is guaranteed to be 7-bit clean and infallibly convertible to UTF-8.
This knocks both of the twenty …
> Fix slow property tests

- tiledb/api/examples/reading_incomplete.rs
- tiledb/api/src/query/buffer.rs
- tiledb/api/src/query/read/callback.rs
- tiledb/api/src/query/read/managed.rs
- tiledb/api/src/query/read/mod.rs
- tiledb/api/src/query/read/output.rs
- tiledb/api/src/query/read/raw.rs
- tiledb/api/src/query/read/typed.rs
- tiledb/api/src/query/write/input.rs
- tiledb/api/src/query/write/mod.rs
This exposes the validity vectors from TileDB which are used to indicate nullness.
> Support for reading and writing validity vectors

- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/query/write/strategy.rs
This does not address the inevitable `proptest-derive` issue that I see when running clippy with nightly, but for some reason that did not appear in the CI output.
> Fix nightly clippy issues

- tiledb/api/examples/reading_incomplete.rs
- tiledb/api/src/datatype/arrow.rs
- tiledb/api/src/datatype/strategy.rs
- tiledb/api/src/query/buffer.rs
- tiledb/api/src/query/read/callback.rs
- tiledb/api/src/query/read/output/arrow.rs
- tiledb/api/src/query/read/output/mod.rs
- tiledb/api/src/query/read/output/strategy.rs
- tiledb/api/src/query/write/strategy.rs
Proptest is used for testing.
RawReadOutput could be either a primitive array or a generic list array.  Arrow `RecordBatch` is just looking for `Arc<dyn Array>`, so we use that as the arrow array output type.
> Implement conversion from RawReadOutput to Arrow array

- tiledb/api/src/array/attribute/arrow.rs
- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/dimension/mod.rs
- tiledb/api/src/array/domain/mod.rs
- tiledb/api/src/array/enumeration/mod.rs
- tiledb/api/src/array/fragment_info.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/context.rs
- tiledb/api/src/error.rs
- tiledb/api/src/filter/list.rs
- tiledb/api/src/filter/mod.rs
- tiledb/api/src/group/mod.rs
- tiledb/api/src/query/conditions.rs
- tiledb/api/src/query/mod.rs
- tiledb/api/src/query/read/raw.rs
- tiledb/api/src/query/subarray.rs
- tiledb/api/src/query/write/mod.rs
- tiledb/api/src/vfs.rs
This removes all access to the underlying raw context pointer except through the `Context::capi_call` method. This method accepts a single argument that is a `FnOnce` callable. This callable must take a single argument which is a `*mut ffi::tiledb_ctx_t` that can be used to pass to all of the FFI calls that require it. The return value should be the i32 result of invoking one of the tiledb FFI functions.
A simple example looks like such:
```rust
pub fn version(&self) -> TileDBResult<i64> {
let mut c_version: std::os::raw::c_int = out_ptr!();
self.capi_call(|ctx| unsafe {
ffi::tiledb_array_schema_get_allows_dups(
ctx, c_schema, &mut c_version
)
})?;
Ok(c_version as i64)
}
```
> Replace capi_return with capi_call

- tiledb/api/examples/reading_incomplete.rs
- tiledb/api/src/query/mod.rs
- tiledb/api/src/query/read/callback.rs
- tiledb/api/src/query/read/mod.rs
- tiledb/api/src/query/read/output/arrow.rs
- tiledb/api/src/query/read/output/mod.rs
- tiledb/api/src/query/read/output/strategy.rs
- tiledb/api/src/query/read/raw.rs
- tiledb/api/src/query/write/strategy.rs
Our primary use case requires us to manifest arrow record batches.  Core has an option to produce arrow-like offsets, so let's use those options instead of re-rolling them ourselves in the Rust layer.
But even on top of that, it makes a lot of sense with the current API design to use element-based offsets.  The buffers we attach to the query API express themselves in terms of a `Unit` type which is some primitive.  By using the element offsets we save the effort from doing arithmetic from the returned query sizes.
The `extra_offset` configuration also enables us to eliminate the `RawReadOutput::nbytes` field, which is now redundant with the last offset.  This change makes the `RawReadOutput` easier to use.
> Configure queries to return arrow-like results, i.e. "extra" offset and element offsets; remove RawReadOutput::nbytes

- .github/workflows/nigthtly-ci.yml
- tiledb/api/src/array/mod.rs
I forgot to set the `ci_nightly` config attribute and clippy has started complaining. Easy fix is easy.
> Fix nightly CI config

- tiledb/api/Cargo.toml
This is to match a change to datafusion 37 in the tables repo.
> Update Arrow dependencies

- tiledb/api/src/array/attribute/arrow.rs
- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/attribute/strategy.rs
- tiledb/api/src/array/dimension/arrow.rs
- tiledb/api/src/array/dimension/mod.rs
- tiledb/api/src/array/dimension/strategy.rs
- tiledb/api/src/array/domain/strategy.rs
- tiledb/api/src/array/enumeration/strategy.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/array/schema/strategy.rs
- tiledb/api/src/datatype/arrow.rs
- tiledb/api/src/datatype/mod.rs
- tiledb/api/src/datatype/physical.rs
- tiledb/api/src/datatype/strategy.rs
- tiledb/api/src/filter/strategy.rs
To date, we were actually only using a few different datatypes for the proptest strategies.  And we were missing all cell val nums other than 1.
This pull request updates our strategies to use all datatypes, and consider other cell val nums as well.
There are a few issues which are revealed by those changes:
- restrictions on RLE and Dictionary filters in pipelines (fixed in this PR)
- multiple-value fill values for attributes (fixed in this PR)
- dimension domain/extent sometimes silently ignored (deferred)
> Remove restrictions on datatypes for proptest strategies

- tiledb/api/src/datatype/mod.rs
- tiledb/api/src/filter/mod.rs
I spent a day today taking another stab at learning the proptest API. So far my FilterListData Strategy is generating about 100k/sec valid cases. During that work I found a couple minor bugs in our Rust logic that contradicted core.
The first bug is a simple typo fixed by doing a `s/Boolean/Blob/`.
The second one is actually interesting. [The C++ code looks like this][1]:
```c++
bool CompressionFilter::accepts_input_datatype(Datatype input_type)  const {
auto this_filter_type = compressor_to_filter(compressor_);
if (this_filter_type == FilterType::FILTER_DOUBLE_DELTA ||
this_filter_type == FilterType::FILTER_DELTA) {
// Delta filters do not accept floating point types.
if (datatype_is_real(
reinterpret_datatype_ != Datatype::ANY ? reinterpret_datatype_ :
input_type)) {
return false;
}
} …
```
> Fix minor bugs

- tiledb/api/examples/query_condition_dense.rs
- tiledb/api/examples/query_condition_sparse.rs
- tiledb/api/src/query/conditions.rs
- tiledb/api/src/query/mod.rs
This is a minor tweak to the query condition API which simplifies the experience for users a bit.  The `struct QueryCondition` is only ever build and then immediately passed to the query builder API.  Any manipulations will be done by the enum.  Given that, why should the user need to build a `struct QueryCondition` at all? Let's just have the query do it.  That's what this PR implements.
> Remove QueryCondition struct, user just provides enum

- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/attribute/strategy.rs
- tiledb/api/src/metadata.rs
When a proptest fails with schema data, we would really like to be able to copy/paste the `Debug` output into a unit test so we can step through the execution of the minimum failing input with ease.
At present there are a number of alterations required in order to copy/paste.  Attribute fill data, for example, looks like:
```
fill: Some(
FillData {
data: Array [
Number(52),
Number(78),
Number(56),
Number(57),
Number(-6),
Number(-81),
Number(-89),
Number(23),
Number(108),
Number(36),
],
nullability: Some(
false,
),
},
)
```
This can probably be copy/pasteable by doing `use serde_json::Value::*` or something along those lines.  But we'd probably rather see something like `data: UInt64([52, 78, 56, 57, -6, -81, -89, 23, 108, 36])`.
This change also is a step towards removing `serde_json` as …
> FillData::data is not json but instead metadata::Value

- tiledb/api/src/query/buffer/mod.rs
- tiledb/api/src/query/write/input.rs
- tiledb/api/src/query/write/mod.rs
This argument was tacked on in prior work, but as we turn more attention to the write side of queries it deserves some proper attention.
Different inputs may behave differently with different `cell_val_num`, or may even error out.  `DataProvider::as_tiledb_input` should return `TileDBResult`, and our existing impls should properly use `cell_val_num`.
> Properly use cell_val_num in DataProvider impls

- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/dimension/mod.rs
- tiledb/api/src/array/fragment_info.rs
- tiledb/api/src/error.rs
- tiledb/api/src/metadata.rs
- tiledb/api/src/query/buffer/arrow.rs
- tiledb/api/src/query/buffer/mod.rs
- tiledb/api/src/query/read/output/mod.rs
- tiledb/api/src/query/read/output/strategy.rs
- tiledb/api/src/query/subarray.rs
- tiledb/api/src/query/write/input/arrow.rs
- tiledb/api/src/query/write/input/mod.rs
- tiledb/api/src/query/write/mod.rs
- tiledb/api/src/range.rs
Previous work turned query read output into arrow data.  This pull request flips that, turning arrow data into query input.
This involves several implementations of `DataProvider` for arrow array types, as well as introducing a similar `TypedDataProvider` which we need to do `impl TypedDataProvider for dyn ArrowArray`.  `DataProvider` has an object create `QueryBuffers` and `TypedDataProvider` has an object return `TypedQueryBuffers`.  These implementations are tested by taking something resembling tiledb query output, turning it into arrow, and then turning the arrow back into the tiledb format.
We also add a new trait `RecordProvider` which we implement for `RecordBatch`, adding a set of named fields to a write query.  This is not tested yet and probably won't be while the write test …
> Implement query input traits for Arrow data

- tiledb/api/src/query/buffer/mod.rs
- tiledb/api/src/query/read/output/mod.rs
We have tests `test_fixed_data_iterator_lifetime` and `test_var_data_iterator_lifetime` which demonstrate unsoundness of an `unsafe` block inside `FixedDataIterator` and `VarDataIterator` respectively.  This unsoundness arises when there is a transfer of ownership of the values data into the iterator, potentially resulting in a situation where an item yielded lives longer than the iterator does.
This pull request fixes that unsoundness by adding a type-level proof that the data passed to the iterator is *borrowed*, not owned.  The user cannot construct an iterator which satisfies the conditions for unsoundness.
> Fix FixedDataIterator and VarDataIterator soundness

- tiledb/api/src/array/fragment_info.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/array/strategy.rs
- tiledb/api/src/group/mod.rs
- tiledb/api/src/lib.rs
- tiledb/api/src/query/subarray.rs
- tiledb/api/src/query/write/strategy.rs
- tiledb/api/src/test_util.rs
- tiledb/api/src/vfs.rs
This removes our usage of the TempDir for tests and instead uses a new TestArrayUri trait. Eventually this will allow us to dynamically change whether tests run against a local file system or a remote cloud service instance.
This does not yet support actually running against the cloud service as that will take more infra setup to get going. However, it should be as simple as creating a new TestCloudUri struct which then implements the TestArrayUri trait. Then the `test_util::get_uri_generator` can return either trait implementation at runtime based on an environment variable or whatever is easiest in CI.
> Replace TempDir with TestArrayUri

- tiledb/api/src/array/dimension/strategy.rs
- tiledb/api/src/array/domain/mod.rs
- tiledb/api/src/array/domain/strategy.rs
- tiledb/api/src/array/schema/arrow.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/array/schema/strategy.rs
- tiledb/api/src/datatype/physical.rs
- tiledb/api/src/query/read/callback.rs
- tiledb/api/src/query/read/mod.rs
- tiledb/api/src/query/strategy.rs
- tiledb/api/src/query/write/strategy.rs
This is the follow-up to #98 , extending the proptest to also work correctly for sparse writes.
Things this pull request had to deal with:
- filters on schema coordinates and dimensions because those can be Float types now
- generating unique values for dimensions when required
There are a few notable tools used to accomplish these goals.
As we've been building out the API we've had more and more reasons to separate handling of floating-point types from integral types for the various enums that can hold both. This pull request encounters yet another, and so we add the `crate::datatype::Integral` trait as a helper for writing generic code over u8, u16, u32, etc.
Another tool added here is an analog of `Iterator::map` for the query callback adapters. We add `map_intermediate`, `map_final`, …
> Proptest for checking correctness of a single sparse write

- tiledb/api/src/datatype/physical.rs
- tiledb/api/src/query/strategy.rs
- tiledb/api/src/query/write/strategy.rs
Story details: https://app.shortcut.com/tiledb-inc/story/48511
> Generating a write input for a sparse array may require generating unique coordinates.
>
> The current strategy generates coordinates which are unique for each dimension individually. If a single dimension is constrained to the domain 0.. 10, for example, then the strategy cannot possibly produce more than 10 records of input, no matter how many other dimensions there are.
> 
> This means that the test generator will never cover the whole space of a sparse dimension.
> 
> The implementation of choosing the unique values within a dimension also is not very smart. It uses proptest::collection::btree_set, which generates a bunch of values and then throws the whole thing away to try again if it is below the requested number of …
> feat: [sc-48511] Fix sparse array write strategy "too many local rejects"

- tiledb/api/src/query/write/strategy.rs
This adds functionality and visibility needed to use the proptests inside of the tables repo.
> Improvements to proptest-strategies write sequence API to enable testing in tables repo

- tiledb/api/src/query/write/strategy.rs
Downstream crates may desire to construct `DenseWriteSequence` or `SparseWriteSequence` without using their `Arbitrary` traits.
(This is a need we currently have in the tables repo)
This pull request adds appropriate `From` and `FromIterator` impls for both.
> pub API for constructing DenseWriteSequence, SparseWriteSequence

- tiledb/api/src/array/mod.rs
- tiledb/api/src/context.rs
This small pull request is a very minor usability enhancement.  The function `Context::object_type` returns an `ObjectType` for whatever it finds at a given URI.
This method currently returns `Option`... but not for any documented reason.  And the one you would expect, that an object is not found at all, is actually an error from inside core.
Why do we return `Option`?  Because of a possible conversion failure from the C value to the `ObjectType` enum.  But that should be an internal error, as indicated the method this PR switches to using instead.
> Remove Option return from Context::object_type

- Cargo.lock
- Cargo.toml
- tiledb/api/Cargo.toml
- tiledb/api/src/query/strategy.rs
- tiledb/test-utils/Cargo.toml
- tiledb/test-utils/src/lib.rs
- tiledb/test-utils/src/strategy/mod.rs
- tiledb/test-utils/src/strategy/records.rs
The strategy produced by `proptest::collection::vec` shrinks very slowly, lopping records off from the end one at a time.  It also stores a value tree for each element of the `Vec`, and shrinks those when the minimum set of elements has been determined.
This strategy is easy to use but is not really right for some of our use cases.  For example, if we want to write a large number of records into tiledb and the test fails, then shrinking the input data one record at a time is hardly sensible.  And shrinking the individual elements, while not worthless, is also not worth the state overhead.
This pull request takes the strategy already written to reason about sparse write inputs, and generalizes it to a new `Records` trait.
A simple experiment shows that on large inputs, this new strategy …
> Alternative strategy for a vector of records

- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/datatype/mod.rs
- tiledb/api/src/datatype/strategy.rs
- tiledb/api/src/group/mod.rs
- tiledb/api/src/metadata.rs
SC-48994 is about adding a DataFusion TableProvider which scans, and later maybe inserts, metadata.
The tables PR which depends on this is [here](https://github.com/TileDB-Inc/TileDB-Tables/pull/17).
> Various metadata API changes and improvements in support of SC-48994

- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/array/schema/strategy.rs
I believe this is what has been responsible for the spurious failures in https://github.com/TileDB-Inc/TileDB-Tables/pull/16 .  When the schema strategy chooses a very large sparse tile capacity, we allocate huge amounts of memory in the query writer, which can lead to OOM in any environment.  The previous limit apparently led to OOMs frequently enough in CI to prevent merging.
This pull request syncs the default limit on sparse tile capacity with the default upper bound on dense array domains.  This bound is much less and should not result in OOMs.
> Reduce DEFAULT_MAX_SPARSE_TILE_CAPACITY to reduce max size of proptest sparse tiles

- tiledb/api/src/query/write/input/arrow.rs
- tiledb/api/src/query/write/input/mod.rs
- tiledb/api/src/query/write/mod.rs
`tiledb-rs` queries use extra offsets for read mode, but not write mode.  This creates some confusion when interacting with raw buffers - a buffer cannot be passed from read query to write query, it has to be adjusted.  It also creates some difficulty with testing and conversion to arrow.
This pull request synchronizes read and write queries in their usage of the extra offset, which simplifies a lot of the testing code and will further pay off in upstream crates and repositories.
> Use 'sm.var_offsets.extra_element=true' for write queries

- tiledb/api/src/datatype/mod.rs
This will enable `Datatype` to be used as the key in a `HashMap`.
> #[derive(Hash)] for Datatype

- Cargo.lock
- tiledb/api/Cargo.toml
Datafusion version 39 uses arrow version 52, so we must update `tiledb-rs` to match first.
> Update to arrow 52.0

- Cargo.lock
- tiledb/test-utils/Cargo.toml
- tiledb/test-utils/src/lib.rs
- tiledb/test-utils/src/signal.rs
This was useful in debugging the recent tables CI issues.  When Rust fails to allocate memory, it terminates the process with SIGABRT which does not bubble up to proptest to print the current test case.  Using this utility I was able to register a callback to print the current test case in response to that SIGABRT, leading to a reproducer I could inspect on my laptop.
It's certainly not production ready, as some of the comments indicate, but I'd like to merge it in case it proves useful again in the future.
> Add test utility to run a callback as a signal handler

- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/dimension/mod.rs
- tiledb/api/src/array/domain/mod.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/query/read/mod.rs
- tiledb/api/src/query/read/output/mod.rs
- tiledb/api/src/query/strategy.rs
Story details: https://app.shortcut.com/tiledb-inc/story/49541
This should fix, or at least significantly diminish the probability of, the "could not allocate memory" issues we observed in `tables` CI.
> chore: [sc-49541] [rs] add memory limit to default allocation strategy for query read buffer

- tiledb/api/src/array/attribute/arrow.rs
- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/attribute/strategy.rs
- tiledb/api/src/array/dimension/arrow.rs
- tiledb/api/src/array/dimension/mod.rs
- tiledb/api/src/array/dimension/strategy.rs
- tiledb/api/src/array/enumeration/strategy.rs
- tiledb/api/src/array/fragment_info.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/datatype/mod.rs
- tiledb/api/src/datatype/strategy.rs
- tiledb/api/src/metadata.rs
- tiledb/api/src/query/read/output/strategy.rs
- tiledb/api/src/query/strategy.rs
- tiledb/api/src/query/subarray.rs
- tiledb/api/src/range.rs
`fn_typed` was our earliest foray into this sort of meta-programming and it predates what has become our preferred style.  Additionally, almost all usages of it immediately bound a new type identifier `type DT = <LT as LogicalType>::PhysicalType`.
This pull request addresses both of those by splitting `fn_typed` into `logical_type_go` and `physical_type_go`, whose purposes are hopefully clear from the names.
> Split fn_typed into logical_type_go and physical_type_go and add example

- tiledb/api/src/array/dimension/mod.rs
- tiledb/api/src/array/domain/mod.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/datatype/physical.rs
- tiledb/api/src/query/mod.rs
- tiledb/api/src/query/subarray.rs
- tiledb/api/src/query/write/strategy.rs
- tiledb/api/src/range.rs
Story details: https://app.shortcut.com/tiledb-inc/story/50382
> In tables we might see a query with multiple predicates on dimensions. Each of these predicates can restrict the subarray we want to select (using range analysis - see technical discussion [49433](https://app.shortcut.com/tiledb-inc/story/49433/technical-design-discussion-for-dense-range-pushdown) ). As we run over the predicates, we want to accumulate the minimal subarray across all predicates.
> 
> If we have "a AND b", then we want to compute the intersection of the range which can satisfy "a" and the range which can satisfy "b" for our subarray.
> 
> If we have "a OR b", then we want to append multiple ranges to the subarray - the range which can satisfy "a" plus the range which can satisfy "b" (and happily, core will …
> feat: [sc-50382] [tables] or [rs] implement accumulating a subarray from the intersection of predicate ranges

- tiledb/api/examples/fragment_info.rs
- tiledb/api/examples/groups.rs
- tiledb/api/examples/multi_range_subarray.rs
- tiledb/api/examples/output/.gitignore
- tiledb/api/examples/query_condition_dense.rs
- tiledb/api/examples/query_condition_sparse.rs
- tiledb/api/examples/quickstart_dense.rs
- tiledb/api/examples/quickstart_sparse_string.rs
- tiledb/api/examples/reading_incomplete.rs
- tiledb/api/examples/using_tiledb_stats.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/context.rs
- tiledb/api/src/group/mod.rs
As written each of our examples creates its array in the current working directory from which you run the example. This clutters the workspace.  This pull request updates the examples to instead write to a consistent output location where we can place a `.gitignore`.
Along the way we fix `Context::object_type` (again - see https://github.com/TileDB-Inc/tiledb-rs/pull/117) to return `None` for paths which do not exist in the absence of I/O errors.
> Consistent output directory for examples

- .github/workflows/pr-build-and-test.yml
- .github/workflows/pr-ci.yml
- .github/workflows/pr-lint.yml
- tiledb/api/src/array/schema/strategy.rs
Story details: https://app.shortcut.com/tiledb-inc/story/45521
The title is not quite right, it should say "tests do not run if linter fails".
This pull request fixes the issue in the title by splitting the linting off into a separate workflow.
> feat: [sc-45521] CI does not run tests if linter fails

- tiledb/api/src/array/attribute/arrow.rs
- tiledb/api/src/array/dimension/arrow.rs
- tiledb/api/src/array/domain/mod.rs
- tiledb/api/src/array/fragment_info.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema/arrow.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/query/strategy.rs
- tiledb/api/src/query/subarray.rs
- tiledb/api/src/query/write/strategy.rs
Some small usability additions as well as a name change: `Domain::ndim` to `Domain::num_dimensions`, to match the style of our other `num_thing` methods.
The underlying functions are already tested, except for the addition to the test code `Cells` but I plan to use that in a branch I'm working on.
> Various API additions and one tweak

- Cargo.lock
- tiledb/api/Cargo.toml
- tiledb/api/build.rs
- tiledb/sys/Cargo.toml
- tiledb/sys/build.rs
- tiledb/utils/src/build.rs
- tiledb/utils/src/lib.rs
Adding $ORIGIN and @loader_path to the RPATH allows users to just place a copy of libtiledb.{so,dylib,dll} next to the binary instead of forcing it's presence in a specific system directory. This should allow for users to be able to play with the binaries created by rustc without having to setup a full build and install of libtiledb.
> Set local rpath lookups for libtiledb

- tiledb/api/src/query/conditions.rs
Story details: https://app.shortcut.com/tiledb-inc/story/52402
Blocks https://app.shortcut.com/tiledb-inc/story/52316/tables-cli-explain-query-panics-with-not-implemented
> For tables we would like details about the ArrayScan operator to appear in EXPLAIN plan output. The verbose EXPLAIN output should include as many details as possible about the scan, including subarrays and query conditions.
To do the above work for tables we must first `impl Display for QueryConditionExpr` in the `api` crate.
> chore: [sc-52402] [rs] impl Display for QueryConditionExpr

- tiledb/api/src/datatype/mod.rs
- tiledb/api/src/range.rs
This function is conceivably useful for test code in crates using `tiledb-rs`.  For example, `tables`.
> Remove cfg(test) for Datatype::iter

- .github/actions/build-tiledb/action.yml
- .github/actions/install-tiledb/action.yml
- .github/workflows/nightly-libtiledb.yml
- .github/workflows/nigthtly-ci.yml
This builds libtiledb once a day and stores it under the `nightly-libtiledb` release tag. This can then be used by all other CI workflows for consuming libtiledb.
> Setup nightly libtiledb builds

- .github/actions/install-tiledb/action.yml
Accidentally forgot to update this to be TileDB-Inc and not my personal fork.
> Fix release repository name

- .github/workflows/nightly-libtiledb.yml
Apparently, the public repostiories have a default permissions setting that prevents this for the entire TileDB-Inc organization.
> Add permissions for uploading release artifacts

- .github/workflows/pr-api-coverage.yml
- .github/workflows/pr-build-and-test.yml
- .github/workflows/pr-lint.yml
The install-tiledb composite action requires that the `GITHUB_TOKEN` be forwarded explicitly.
> Fix PR CI Install TileDB Step

- tiledb/api/examples/using_tiledb_stats.rs
- tiledb/api/src/array/schema/arrow.rs
- tiledb/api/src/filter/strategy.rs
- tiledb/api/src/query/read/output/mod.rs
- tiledb/api/src/query/read/raw.rs
- tiledb/api/src/query/strategy.rs
- tiledb/api/src/query/write/strategy.rs
- tiledb/sys/ignored.rs
- tiledb/sys/src/array_type.rs
- tiledb/sys/src/schema.rs
- tiledb/test-utils/src/strategy/records.rs
- tiledb/utils/src/option.rs
This lint was introduced into Rust nightly recently.
https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph
"Documentation will show the first paragraph of the doscstring in the summary page of a module, so having a nice, short summary in the first paragraph is part of writing good docs."
> Fix nightly lint 'first doc comment paragraph is too long'

- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/domain/strategy.rs
- tiledb/api/src/array/schema/strategy.rs
- tiledb/api/src/error.rs
- tiledb/api/src/lib.rs
- tiledb/api/src/query/strategy.rs
- tiledb/api/src/tests/examples/mod.rs
- tiledb/api/src/tests/examples/sparse_all.rs
- tiledb/api/src/tests/mod.rs
The commits in this PR are essentially unrelated to each other, the common theme merely being that these are all changes I made while working on #113 .  I decided to pull them out so aggregates will take up a greater percentage of the lines of code in their introductory PR.
Anyway, looking at this commit-by-commit is not a bad idea; notes on each below.
[Add asserts to attribute_default about nullability](https://github.com/TileDB-Inc/tiledb-rs/commit/70fb2cfccb2636f46317b242178df5fd1e853e71) - we make assumptions about default core library behavior in a few places, so let's make sure if it ever changes we get a concise alert.
[strat_dimension, strat_attribute, strat_field](https://github.com/TileDB-Inc/tiledb-rs/commit/04a381ae9c2d693296d75e57ff5e0a5ac75a88eb) - proptest strategies for …
> Pull out testing / generally useful code from the aggregate API PR

- tiledb/api/src/array/dimension/mod.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/tests/examples/mod.rs
- tiledb/api/src/tests/examples/quickstart.rs
- tiledb/api/src/tests/examples/sparse_all.rs
- tiledb/api/src/tests/mod.rs
This is similar to what we have done in `tables`, i.e. put this example schema in a place where it is easy to re-use throughout our many test modules.
> Refactor into `tests/examples/quickstart.rs`

- tiledb/api/src/array/domain/strategy.rs
I'm not sure whether something changed recently, but I had a look at this test (whose goal is to ensure that shrinking a domain reduces the number of dimensions) and the way that it runs appears to spend most of the time shrinking the *name* of the domain.
I don't think that shrinking the name is something we should never do, but it certainly isn't worth waiting a minute for each time we run this test.
I've chosen to ignore this test rather than do something else because I think we should revisit the domain shrinking with a custom implementation and test that.  Removing the test also seems acceptable under this view.
> ignore domain_shrinking test

- tiledb/api/src/datatype/physical.rs
- tiledb/api/src/query/conditions.rs
- tiledb/api/src/query/subarray.rs
- tiledb/api/src/range.rs
The purpose of this PR is to enable deriving Eq and Hash for ArrayScanFilterPushDown in the tables repo.
We need to do *that* so that we can put ArrayScanFilterPushDown into custom logical plan nodes, which must impl Eq and Hash.
We need to write custom logical plan nodes which embed ArrayScanFilterPushDown in order to push down aggregates (this is not exactly 100% true but it does lead to a nice implementation).
The only philosophical issue at hand is whether it is correct to do this because of the floating-point variants.  These are handled using our `BitsEq` and `BitsHash` traits respectively, which I claim accounts for correctness.  So, philosophically: floating point numbers do not impl Eq or Hash due to NaN.  I don't anticipate that we particularly care about propagating `NaN != …
> impl Eq and Hash for SubarrayData and QueryConditionExpr

- tiledb/api/src/array/domain/strategy.rs
- tiledb/api/src/array/enumeration/strategy.rs
- tiledb/api/src/array/schema/strategy.rs
- tiledb/api/src/filter/strategy.rs
- tiledb/api/src/lib.rs
- tiledb/api/src/query/strategy.rs
- tiledb/api/src/query/write/strategy.rs
A goal we haven't focused on much yet is configuring our nightly runs to generate more complicated inputs and test cases in our proptests.
This pull request implements one step towards this goal - adding environment variables for overriding the default values used in our array schema tests.
Toying with some of these environment variables exposed some bugs which are also incidentally addressed here, such as SC-51250
We also `impl Arbitrary for EnumerationData` along the way to this change.
> Configure array schema proptest constants using environment; and some incidentals

- Cargo.toml
- tiledb/api/src/array/domain/strategy.rs
- tiledb/api/src/array/enumeration/strategy.rs
- tiledb/api/src/array/schema/strategy.rs
- tiledb/api/src/lib.rs
- tiledb/api/src/query/strategy.rs
- tiledb/api/src/query/write/strategy.rs
- tiledb/api/src/strategy.rs
As requested in [this comment](https://github.com/TileDB-Inc/tiledb-rs/pull/157#pullrequestreview-2287147756), moving all the proptest strategy configuration to a single file is useful for maintainability/discoverability.
Note that the usage of `LazyLock` requires rust version 1.80.
> Move proptest strategy configurations into a single file

- tiledb/api/src/filter/strategy.rs
- tiledb/api/src/query/write/strategy.rs
- tiledb/sys/ignored.rs
- tiledb/sys/src/array.rs
- tools/api-coverage/src/main.rs
These filters coupled with a checksum filter can produce an array that breaks when read. See SC-48409
> Disable bit and byte shuffle filters for writes

- tiledb/test-utils/src/strategy/meta.rs
- tiledb/test-utils/src/strategy/mod.rs
- tiledb/test-utils/src/strategy/records.rs
- tiledb/test-utils/src/strategy/sequence.rs
Story details: https://app.shortcut.com/tiledb-inc/story/55233
`RecordsValueTree` is an alternative to `proptest::collection::VecValueTree` for shrinking down a collection of values.
We have observed a few times in our tests which use this a panic during the shrinking process tracing to `RecordsValueTree`.  When we have such a panic, proptest shrinking iterations abort without printing the seed used to generate the failing input (or the current failing input).
`RecordsValueTree`'s shrinking logic was panicking in the expression `self.explore_results[i].take().unwrap()`.  This turned out to be a logical out-of-bounds access.  `i` was previously bounded by `self.explore_results.len()`, but not all of the indices would be filled in if there were fewer records than `explore_results`.
The fix …
> chore: [sc-55233] [rs] panic in RecordsValueTree::simplify prevents proptest from dumping seed which led to bad input

- tiledb/api/src/array/attribute/strategy.rs
- tiledb/api/src/array/dimension/strategy.rs
- tiledb/api/src/array/domain/strategy.rs
- tiledb/api/src/array/schema/strategy.rs
- tiledb/api/src/filter/list.rs
- tiledb/api/src/filter/strategy.rs
- tiledb/test-utils/src/strategy/mod.rs
- tiledb/test-utils/src/strategy/sequence.rs
Story details: https://app.shortcut.com/tiledb-inc/story/56223
This pull request adds custom `proptest::strategy::ValueTree` implementations for `SchemaData` and friends.  This is beneficial for taking control of the shrinking algorithm but also allows us to construct a shrinkable ValueTree from a SchemaData, which will be very useful for debugging issues which originate outside of proptest.
The implementations ended up surprisingly simple: each `ThingValueTree` struct has fields which roughly correspond to `ThingData`.  `ValueTree::current` becomes trivial; `ValueTree::simplify` and `ValueTree::complicate` simply attempt to simplify or complicate fields in the order that we write them down.
Consider `SchemaValueTree`.  The first way we would want to shrink a schema is by identifying the …
> chore: [sc-56223] [rs] implement custom proptest ValueTree for schema

- tiledb/api/src/array/mod.rs
- tiledb/api/src/config.rs
- tiledb/api/src/query/strategy.rs
I expect to use this functionality for https://app.shortcut.com/tiledb-inc/story/56603/tables-test-error-round-trip-to-from-arrow-affects-sort-order-which-leads-to-logical-comparison-mismatch-when-there-are-duplicate
> Add function to test Cells to identify groups of adjacent equal keys

- tiledb/pod/src/array/schema/strategy.rs
`proptest::option::weighted` panics on inputs of 0.0 and 1.0.  This pull request adds checks for those values and provides an alternate strategy which implements the request.
> Robustness of attribute_enumeration_likelihood

- Cargo.lock
- tiledb/common/Cargo.toml
- tiledb/common/src/range.rs
`SingleValueRange` is essentially a dynamically-typed `std::ops::Range`.  This pull request implements conversions between the two.
I had this hanging around in a `git stash` and figured I'd clear it out.  I'm not sure what my original intent was but this seems potentially useful... or at least not harmful.
> impl conversions between RangeInclusive and SingleValueRange

- tiledb/api/src/config.rs
Add more `CommonOption`s which we use when reading from `cloud.json` in TileDB-Tables. Part of [SC-54120](https://app.shortcut.com/tiledb-inc/story/54120/support-reading-cloud-config-api-tokens-from-tiledb-cloud-json).
Adds new tests.
> Add more `CommonOption`s

- tiledb/api/src/array/attribute/mod.rs
- tiledb/api/src/array/enumeration/mod.rs
- tiledb/api/src/array/fragment_info.rs
- tiledb/api/src/array/mod.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/config.rs
- tiledb/api/src/context.rs
- tiledb/api/src/error.rs
- tiledb/api/src/filesystem.rs
- tiledb/api/src/group/mod.rs
- tiledb/api/src/lib.rs
- tiledb/api/src/query/mod.rs
- tiledb/api/src/stats.rs
- tiledb/api/src/string.rs
In `tiledb-tables`, we've begun to declare at least one `Error` enum per module.  If a module `foo` calls a function from a module `bar`, then `foo::Error` has an enum variant approximating `Bar(bar::Error)`.  This can help build a causality chain in error output.
We have discussed bringing this error style into `tiledb-rs`, and this pull request is a foray into doing so.  We begin with the core of `tiledb-rs`, `Context::capi_call`.  This pull request adds `CApiError` which is returned by `Context::capi_call`.  The rest of the changes fell out of that in some way.
There are a few `// SAFETY` comments for new `unwrap`s.  These are added in situations where we try to convert a value returned from tiledb into one of the `tiledb-rs` enums.  The presupposition is that if libtiledb returned …
> `tiledb-rs` error styling part 1: `Context::capi_call` returns its own error type

- tiledb/api/Cargo.toml
- tiledb/api/examples/query_condition_dense.rs
- tiledb/api/examples/query_condition_sparse.rs
- tiledb/api/src/query/condition/mod.rs
- tiledb/api/src/query/condition/strategy.rs
- tiledb/api/src/query/mod.rs
This pull request implements a custom `ValueTree` for query conditions.  This initial pass constructs a ValueTree given a query condition and shrinks the combination clauses.
Without a strategy to _generate_ a query condition, this can only be used to shrink to shrink one that has already identified, e.g.
```
use strategy_ext::StrategyExt;
Just(my_query_condition).value_tree_map(|vt| QueryConditionValueTree::new(vt.current())
```
The hope is that this can be useful for customer cases.  And someday when we build strategies to generate query conditions it can be useful for shrinking those, too.
> First pass at proptest ValueTree for query condition

- tiledb/api/src/array/enumeration/mod.rs
- tiledb/api/src/query/condition/mod.rs
While writing tests for [SC-51070](https://app.shortcut.com/tiledb-inc/story/51070/tables-turn-datafusion-in-list-predicate-into-setmembership-query-condition) I stumbled into the in-capability of checking what the values inside a query condition expression actually are using a pub API.
This pull request changes the in-capability to a capability.
> Add public accessors to query condition data

- tiledb/sys/build.rs
For some reason, the `pkg-config` that comes in the manylinux containers does not strip quotes. This avoids using the built-in variables and instead just grabs the prefix, strips quotes, and manually appends `lib` for now. Theoretically that could bite me later if something moves to `lib64` but I'll deal with that if and when it happens.
> chore(build): Strip quotes from tiledb prefix

- Cargo.lock
- Cargo.toml
We'll need this until we upgrade to Arrow 54.2.1 or newer.
https://github.com/apache/arrow-rs/issues/7209
> build(chrono): Pin chrono to 0.4.39

- .github/actions/install-tiledb/action.yml
The `releases.csv` on `TileDB-Inc/TileDB` releases has extra spaces at the end of each line which caused our sha256 comparisons to fail. This fixes things by just trimming the values read.
> chore(ci): Fix install-tiledb action

- test-utils/signal/src/lib.rs
- tiledb/pod/src/query/subarray.rs
This update addresses the `manual_contains` clippy lint.
> fix(lint): Fix new nightly lints

- .github/workflows/nightly-ci.yml
- tiledb/api/src/query/strategy/tests.rs
- tiledb/common/src/datatype/logical.rs
- tiledb/common/src/datatype/mod.rs
The signed-ness of `char` is architecture-dependent.  We were previously using `i8` as the physical type.  Now that we are running query conditions this has manifested in test failures when comparing against negative values on architectures where `char` is actually unsigned.
This pull request fixes the issue by using `c_char` for the physical type of `Datatype::Char`.  `c_char` is just a [type alias](https://doc.rust-lang.org/std/ffi/type.c_char.html) for `u8` or `i8` depending on the architecture.
I also increased the shrinking bounds for nightly runs - we expect infrequent failures and when they do show up the smaller the better.  The changes here increase the number of shrinking iterations to a large number but bounds the shrink time at one hour.
> fix: physical type of `Datatype::Char` is architecture-dependent

- .github/scripts/generate-package-matrix.py
- .github/workflows/packages.yml
The packaging builds managed to get themselves into a weird state which also causes nightlies to fail. This fixes the package builds by pinning the manylinux container to a version that has CMake<4.0 which should unblock nightlies as well.
> chore(ci): Fix package builds

- tiledb/common/src/datatype/arrow.rs
We caught a proptest failure because we translate a fixed size list of length 1, to a non-list version of the contained datatype. I.e., we changed the faux data type `[u32; 1]` to `u32`.
> fix: Set the minimum fixed sized list to 2

- tiledb/common/src/datatype/physical.rs
We've recently seen the following appear in PR CI:
```
thread 'tests::query_condition_and' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proptest-1.6.0/src/num/float_samplers.rs:462:1:
invalid range
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
but it turns out this has also failed in at least one nightly, which was reported in #231 .
The panic arises when `proptest-rs` asserts that the range it wants to sample is non-empty:
```
assert!(high - low > 0., "invalid range");
```
Breaking here with a debugger revealed that we have a range `-0..=0` which fails this assertion.
When does the `query_condition_and` test sample ranges? To construct atomic predicates for query conditions it samples the domain of its input (it does …
> fix: BitsEq/BitsOrd/BitsHash impls for f32 and f64 to treat 0 == -0

- tiledb/api/src/array/schema/arrow.rs
- tiledb/api/src/array/schema/mod.rs
- tiledb/api/src/array/schema/pod.rs
- tiledb/api/src/query/strategy/tests.rs
- tiledb/api/src/tests/examples/sparse_all.rs
- tiledb/pod/src/array/schema/mod.rs
- tiledb/pod/src/array/schema/strategy.rs
The standard nomenclature is "validity".  This pull request changes the `tiledb-rs` functions and fields to use that instead of "nullity".  This is a breaking change since it affects some public fields and functions.
> chore: Change 'nullity' to 'validity' in field names
